baseURL: "https://surajkumar.me/" 
title: Suraj Kumar
paginate: 20
theme: PaperMod

assetsDir: "static" # so that the theme picks up the images from static folder properly

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    # twitter: pmichaillat

taxonomies:
    tag: tags

# For the menu on the top after you have browsed intially
menu:
    main:
        - name: Notes
          url: /notes/
          weight: 1
        - name: Papers
          url: /papers/
          weight: 2
        # - name: Projects
        #   url: /projects/
        #   weight: 3
        - name: Codes
          url: https://github.com/iamsurajkumar
          weight: 3
        # - name: Tags
        #   url: /tags/
        #   weight: 4 
        - name: About
          url: /about/
          weight: 4    
        # - name: Newsletter
        #   url: https://macrolearner.substack.com
        #   weight: 5

params:
    description: "I am a Research Associate at CAFRAL. Previously, I have worked at Goldman Sachs, American Express and Credit Suisse. I am interested in Macroeconomics, Finance and Econometrics"
    author: Suraj Kumar
    # googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false # i kept it at false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    # For the homepage
    profileMode:
          enabled: true
          title: Suraj Kumar
          subtitle: "I am a Research Associate at CAFRAL. Previously, I have worked at Goldman Sachs, American Express and Credit Suisse. I am interested in Macroeconomics, Finance and Econometrics"
          imageUrl: "images/picture.jpeg"
          imageWidth: 170
          imageHeight: 170
          imageTitle: Suraj Kumar
          buttons:
            - name: Notes
              url: /notes/
            - name: Papers
              url: /papers/
            # - name: Design
            #   url: /design/
    socialIcons:
        - name: CV
          url: https://drive.google.com/file/d/1AcrZLPlqCQaSWEStJ8tgs57_oQhAehMP/view?usp=sharing
        - name: Email
          url: "mailto:surajdhunna@gmail.com"
        # - name: Location
        #   url: /location/
        # - name: Office Hours
        #   url: /officehours/
        # - name: Google Scholar
        #   url: "https://scholar.google.com/citations?user=cL23w-4AAAAJ"
        # - name: YouTube
        #   url: "https://www.youtube.com/@pmichaillat"
        - name: GitHub
          url: "https://github.com/iamsurajkumar"
        # - name: Substack
        #   url: "https://macrolearner.substack.com"

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Suraj Kumar"
      icon: /images/flaticon-writing.png
      iconHeight: 18
    fuseOpts:
            isCaseSensitive: false
            shouldSort: true
            location: 0
            distance: 1000
            threshold: 0.4
            minMatchCharLength: 0
            keys: ["title", "permalink", "summary", "content"]
markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
